services:
  - type: web
    name: moneyflow
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /service-worker.js
        name: Cache-Control
        value: no-cache
